listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - Hub
  - 生活鯖
  bind_local_address: true
  host: 0.0.0.0:21131
  max_players: 50
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: null
  admin:
  - bungeecord.command.alert
  - fallback.admin
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: 09ef3f89-4872-4850-a17e-d163b51b6b8f
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  hub:
    motd: |-
      &r&bいるしあ！さあ～ば～ &r&8[&r&a1.16.5-1.18.1&r&8]&r
      &r
    address: 192.168.0.102:21129
    restricted: false
  生活鯖:
    motd: |-
      &r&bいるしあ！さあ～ば～ &r&8[&r&a1.16.5-1.18.1&r&8]&r
      &r
    address: 192.168.0.102:21121
    restricted: false
  Server-iru:
    motd: |-
      &r&bいるしあ！さあ～ば～ &r&8[&r&a1.16.5-1.18.1&r&8]&r
      &r
    address: 1:25565
    restricted: false
